# -*- coding: utf-8 -*-
"""Avaliação Individual RA1-CB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X41iU6T5oHsK394wof4a6DAwp2S7MUBT

# Instruções:
Para a realização desta tarefa você precisa fazer uma cópia deste carderno de questões para a sua conta. Você responderá a questão colando no AVA o link para a sua cópia contendo as suas respostas. 

Se encontrar qualquer problema de compartilhamento, salve o seu carderno, contendo as suas soluções, no Github (Arquivo, Salvar no Github) e poste o link do github no canvas.

Todas as questões precisam ser resolvidas algébrica e computacionalmente. Usando todos os recursos computacionais disponíveis na internet. Mas, você não pode consultar outros seres humanos. 

**Não se equeça de preencher seu nome nesta célula:**
# Leandro de Carvalho Medeiros

# Questão 1: 
Um investimento inicial de $1000$ Reais rende juros compostos a uma taxa de 8% ao ano. Faça um gráfico que mostre como o valor do investimento varia com o tempo e determine qual será o valor do investimento após 10 anos. Utilize a equação $V = P * (1 + r)^t$, onde $P$ é o valor principal do investimento, $r$ é a taxa de juros anual (em decimal) e $t$ é o tempo decorrido em anos.
"""

import matplotlib.pyplot as plt

inve = []
P = 1000
r = 0.08
plt.xlabel('Anos')
plt.ylabel('Valor do Investimento')

for t in range(1,11):
  V = P * (1 + r)**t
  inve.append(V)

plt.plot([1,2,3,4,5,6,7,8,9,10],[inve[0],inve[1],inve[2],inve[3],inve[4],inve[5],inve[6],inve[7],inve[8],inve[9]])
